# Generated by Django 5.2.8 on 2025-12-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('direccion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('imagen', models.CharField(default='', max_length=500)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.departamento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('es_promocion', models.BooleanField(default=False)),
                ('motivo', models.CharField(default='', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_previo', models.PositiveIntegerField(default=0)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
            ],
        ),
    ]
