# Generated by Django 5.2.8 on 2025-12-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_precio_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialinventario',
            old_name='stock_actual',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='historialinventario',
            name='stock_previo',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
