# Generated by Django 5.2.8 on 2025-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_stock_actual_historialinventario_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinventario',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
