# Generated by Django 5.2.8 on 2025-12-01 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_historialinventario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinventario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
