# Generated by Django 5.2.9 on 2025-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_historialinventario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(default='', max_length=20),
        ),
    ]
